{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "fb5c66d3-2d21-4336-a613-afe4a3456da6",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Requirement already satisfied: pyrealsense2 in c:\\users\\user\\anaconda3\\envs\\torchtest\\lib\\site-packages (2.56.5.9235)\n",
      "Note: you may need to restart the kernel to use updated packages.\n"
     ]
    }
   ],
   "source": [
    "pip install pyrealsense2"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "f1a9a667-9b4b-472a-8158-d35356359724",
   "metadata": {},
   "outputs": [],
   "source": [
    "import pyrealsense2 as rs\n",
    "import cv2\n",
    "import numpy as np\n",
    "import os\n",
    "import re\n",
    "\n",
    "class realsense_camera:\n",
    "    is_opened = False\n",
    "    config = None\n",
    "    intr = None\n",
    "\n",
    "    def __init__(self, height=480, width=640, fps=30, use_color=True):\n",
    "        self.height = height\n",
    "        self.width = width\n",
    "        self.fps = fps\n",
    "        self.use_color = use_color\n",
    "\n",
    "        # RealSense 파이프라인 & 설정\n",
    "        pipeline = rs.pipeline()\n",
    "        config = rs.config()\n",
    "\n",
    "        pipeline_wrapper = rs.pipeline_wrapper(pipeline)\n",
    "        self.config = config\n",
    "        self.pipeline = pipeline\n",
    "        self.pipeline_wrapper = pipeline_wrapper\n",
    "\n",
    "        # 디바이스 연결 체크\n",
    "        if self.can_connect():\n",
    "            pipeline_profile = config.resolve(pipeline_wrapper)\n",
    "            device = pipeline_profile.get_device()\n",
    "\n",
    "            # RGB 카메라 있는지 체크\n",
    "            found_rgb = False\n",
    "            for s in device.sensors:\n",
    "                if s.get_info(rs.camera_info.name) == 'RGB Camera':\n",
    "                    found_rgb = True\n",
    "\n",
    "            if not found_rgb:\n",
    "                self.use_color = False\n",
    "\n",
    "            # RGB 스트림 설정\n",
    "            if self.use_color:\n",
    "                config.enable_stream(rs.stream.color, width, height, rs.format.bgr8, fps)\n",
    "\n",
    "            # 파이프라인 시작\n",
    "            if self.can_connect() and self.use_color:\n",
    "                self.is_opened = True\n",
    "                pipeline.start(config)\n",
    "                self.intr = pipeline.get_active_profile().get_stream(\n",
    "                    rs.stream.color\n",
    "                ).as_video_stream_profile().get_intrinsics()\n",
    "\n",
    "    def get_intrinsics(self):\n",
    "        return self.intr\n",
    "\n",
    "    def set(self, num, value):\n",
    "        # 해상도 / FPS 변경\n",
    "        if num == cv2.CAP_PROP_FRAME_HEIGHT:\n",
    "            self.height = int(value)\n",
    "        elif num == cv2.CAP_PROP_FRAME_WIDTH:\n",
    "            self.width = int(value)\n",
    "        elif num == cv2.CAP_PROP_FPS:\n",
    "            self.fps = int(value)\n",
    "\n",
    "        if self.is_opened:\n",
    "            # 스트림 재설정\n",
    "            self.config.disable_all_streams()\n",
    "            if self.use_color:\n",
    "                self.config.enable_stream(\n",
    "                    rs.stream.color,\n",
    "                    self.width,\n",
    "                    self.height,\n",
    "                    rs.format.bgr8,\n",
    "                    self.fps\n",
    "                )\n",
    "            if self.can_connect():\n",
    "                self.pipeline.stop()\n",
    "                self.pipeline.start(self.config)\n",
    "                if self.use_color:\n",
    "                    self.intr = self.pipeline.get_active_profile().get_stream(\n",
    "                        rs.stream.color\n",
    "                    ).as_video_stream_profile().get_intrinsics()\n",
    "\n",
    "    def get(self, num):\n",
    "        if num == cv2.CAP_PROP_FRAME_HEIGHT:\n",
    "            return self.height\n",
    "        elif num == cv2.CAP_PROP_WIDTH:\n",
    "            return self.width\n",
    "        elif num == cv2.CAP_PROP_FPS:\n",
    "            return self.fps\n",
    "\n",
    "    def can_connect(self):\n",
    "        # config의 유효성 및 카메라 연결 여부 체크\n",
    "        try:\n",
    "            return self.config.can_resolve(self.pipeline_wrapper)\n",
    "        except Exception:\n",
    "            return False\n",
    "\n",
    "    def isOpened(self):\n",
    "        return self.is_opened\n",
    "\n",
    "    def release(self):\n",
    "        if self.pipeline is not None:\n",
    "            if self.isOpened():\n",
    "                if self.can_connect():\n",
    "                    self.pipeline.stop()\n",
    "\n",
    "    def read(self):\n",
    "        \"\"\"컬러 프레임만 읽기\"\"\"\n",
    "        try:\n",
    "            frames = self.pipeline.wait_for_frames(100)\n",
    "            if self.use_color:\n",
    "                color_frame = frames.get_color_frame()\n",
    "                if not color_frame:\n",
    "                    return False, None\n",
    "                color_image = np.asanyarray(color_frame.get_data())\n",
    "            else:\n",
    "                color_image = np.zeros((self.height, self.width, 3), dtype=np.uint8)\n",
    "            return True, color_image\n",
    "        except Exception:\n",
    "            return False, None\n",
    "\n",
    "\n",
    "def get_next_save_index(ext=\".png\", search_dir=\".\"):\n",
    "    \"\"\"\n",
    "    search_dir 안에 있는 000.png, 001.png ... 파일 중\n",
    "    가장 큰 번호를 찾고, 그 다음 번호를 리턴.\n",
    "    파일이 없으면 0부터 시작.\n",
    "    \"\"\"\n",
    "    pattern = re.compile(rf\"^(\\d+){re.escape(ext)}$\")\n",
    "    max_idx = -1\n",
    "\n",
    "    try:\n",
    "        for fname in os.listdir(search_dir):\n",
    "            match = pattern.match(fname)\n",
    "            if match:\n",
    "                idx = int(match.group(1))\n",
    "                if idx > max_idx:\n",
    "                    max_idx = idx\n",
    "    except FileNotFoundError:\n",
    "        pass\n",
    "\n",
    "    return max_idx + 1  # 없으면 0, 있으면 max+1\n",
    "\n",
    "\n",
    "if __name__ == \"__main__\":\n",
    "\n",
    "    # ===== 저장 폴더 설정 =====\n",
    "    category = 'cube'\n",
    "    save_category = f\"./data/{category}/train/good\"      # 나중에 \"anomaly\" 등으로 변경\n",
    "    #save_category = f\"./data/{category}/test/good\"\n",
    "    #save_category = f\"./data/{category}/test/anomaly\"\n",
    "    save_dir = save_category\n",
    "    os.makedirs(save_dir, exist_ok=True)\n",
    "    # =========================\n",
    "\n",
    "    # ===== 센터 크롭 사이즈 (정사각형) =====\n",
    "    # 예: 512 -> 512x512 센터 크롭\n",
    "    crop_size = 512\n",
    "    # =====================================\n",
    "\n",
    "    cam = realsense_camera(use_color=True)\n",
    "    # 해상도 / FPS 설정\n",
    "    cam.set(cv2.CAP_PROP_FRAME_WIDTH, 1280)\n",
    "    cam.set(cv2.CAP_PROP_FRAME_HEIGHT, 720)\n",
    "    cam.set(cv2.CAP_PROP_FPS, 30)\n",
    "\n",
    "    if cam.isOpened():\n",
    "        # 해당 폴더 안에서 이어서 번호 붙이기\n",
    "        save_idx = get_next_save_index(ext=\".png\", search_dir=save_dir)\n",
    "        print(f\"Save dir: {save_dir}, start index: {save_idx}\")\n",
    "\n",
    "        while True:\n",
    "            ret, frame = cam.read()\n",
    "            if not ret or frame is None:\n",
    "                continue\n",
    "\n",
    "            # ===== 센터 정사각형 크롭 =====\n",
    "            h, w = frame.shape[:2]\n",
    "            # crop_size가 이미지보다 크면 자동으로 줄이기\n",
    "            size = min(crop_size, h, w)\n",
    "\n",
    "            x1 = (w - size) // 2\n",
    "            y1 = (h - size) // 2\n",
    "            x2 = x1 + size\n",
    "            y2 = y1 + size\n",
    "\n",
    "            frame_cropped = frame[y1:y2, x1:x2]\n",
    "            # =================================\n",
    "\n",
    "            cv2.imshow(\"color\", frame_cropped)\n",
    "\n",
    "            key = cv2.waitKey(1) & 0xFF\n",
    "\n",
    "            # q → 종료\n",
    "            if key == ord('q'):\n",
    "                break\n",
    "\n",
    "            # s → 크롭된 이미지 저장\n",
    "            elif key == ord('s'):\n",
    "                filename = os.path.join(save_dir, f\"{save_idx:03d}.png\")\n",
    "                cv2.imwrite(filename, frame_cropped)\n",
    "                print(\"Saved:\", filename)\n",
    "                save_idx += 1\n",
    "\n",
    "    cam.release()\n",
    "    cv2.destroyAllWindows()"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "TorchTest",
   "language": "python",
   "name": "torchtest"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.25"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
